@startuml
skinparam monochrome false
skinparam packageStyle rectangle
skinparam shadowing true
skinparam classAttributeIconSize 0
hide methods

class Login {
    + email: String
    + password: String
}

@enduml
