@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Register a new user

autonumber

actor "User" as User
participant ":System" as System

activate User

    User -> System : requests to register a new user
    activate System

        System --> User : requests data (i.e. name, email, username,\n phone number, password)
    deactivate System

    User -> System : types requested data
    activate System

        System --> User : displays operation success (e.g., "Registration successful")
    deactivate System
@enduml
