@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing true
'skinparam linetype ortho
skinparam classAttributeIconSize 0
hide circle
hide methods
'left to right direction

class User {
    name
    emailAddress
    phoneNumber
}

class Role {
    designation
}

class Item {
    designation
    condition
    image
}

class Category {
    designation
}

class Advertisement{
    designation
    initialDate
    finalDate
    address
    status
    '(active, pending, closed)
}

class Request {
    status
    '(pending, canceled, denied/rejected, accepted, donated/done)
}

class Tip {
    title
    description
}

class Like {
}

Item "0..*" -left- "1" Category : belongs to a \t >
Advertisement "1" -- "1" Item : contains an \t >
User "1" -- "0..*" Advertisement : create >
User "1" -- "0..*" Request : references <
Request "0..*" -- "1" Advertisement : receives <
User "1" -- "0..*" Like : makes >
Like "0..*" -left- "1" Tip : references >
"User" "0..*" - "1" Role : has \t >
@enduml