@startuml
skinparam monochrome false
skinparam packageStyle rectangle
skinparam shadowing true
left to right direction
skinparam classAttributeIconSize 0
hide circle
hide methods

class Client {
    name
    emailAddress
    phoneNumber
    password
    role
}

class Category {
    - id
    - designation
}

class Item {
    - id: String
    - designation
    - condition
    - image
}

class Advertisement {
    - id: String
    - designation
    - initialDate
    - finalDate
    - address
}

enum AdvertisementStatus {
    designation
}

note left of AdvertisementStatus
Active, Pending or Closed
endnote

' --- Associações ---
Client "1" -- "0..*" Advertisement : owns
Advertisement "1" -- "1" Item : has >
Item "0..*" -- "1" Category: categorized >
Advertisement "1" -- "1" AdvertisementStatus: has >
@enduml