@startuml
skinparam packageStyle rectangle
skinparam shadowing false
skinparam classAttributeIconSize 0

class User {
    - name: String
    - emailAddress: String
    - phoneNumber: String
    - password: String
    - role: String
}

class Item {
    - designation: String
    - condition: String
}

class Advertisement {
    - id: String
    - designation: String
    - initialDate: Date
    - finalDate: Date
    - address: String
    - images: String[]
    - status: AdvertisementStatus
    + deleteAdvertisement(): boolean
}

class Category {
    - name: String
}

class Location {
    - city: String
    - state: String
}

class AdvertisementController {
    + searchAdvertisement(category, location, keyWords)
    + deleteAdvertisement(advertisementId)
}

class AdvertisementService {
    + searchAdvertisement(category, location, keyWords)
    + deleteAdvertisement(advertisementId)
}

class AdvertisementRepository {
    + searchAdvertisement(category, location, keyWords)
    + deleteAdvertisement(advertisementId)
}

' --- Associações ---
User "1" -- "0..*" Advertisement : requests
Advertisement "1" -- "1" Item : has >
Advertisement "1" -- "1" Category : belongs to >
Advertisement "1" -- "1" Location : located in >

AdvertisementController ..> AdvertisementService
AdvertisementService ..> AdvertisementRepository
AdvertisementRepository "1" --> "*" Advertisement : advertisement

@enduml
