@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

actor Manager as M
participant ":CreateCategoryUI" as UI
participant ":CategoryController" as CTRL
participant ":CategoryService" as SERV
participant ":CategoryRepository" as REPO
participant "category\n:Category" as CATEGORY

activate M

    M -> UI : asks to create a new category
    activate UI

        UI --> M : requests data (designation)
    deactivate UI

    M -> UI : types requested data and submits
    activate UI

        UI -> CTRL : createCategory(category)
        activate CTRL

            CTRL -> SERV : createCategory(category)
            activate SERV

                SERV -> REPO : save(category)
                activate REPO

                    REPO --> SERV : category saved
                deactivate REPO

                SERV --> CTRL : category created
            deactivate SERV

            CTRL --> UI : category created
        deactivate CTRL

        UI --> M : confirmation message
    deactivate UI

deactivate M

@enduml
