@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

actor Manager as M
participant ":CreateCategoryUI" as UI
participant ":CategoryController" as CTRL
participant ":CategoryService" as SERV
participant ":CategoryRepository" as REPO
participant ":CategoryMapper" as MAPPER

participant "categoryDTO\n:CategoryDTO" as DTO
participant "savedCategoryDTO\n:CategoryDTO" as SAVEDDTO


participant "savedCategory\n:Category" as SAVEDCATEGORY

participant "category\n:Category" as CATEGORY

activate M

    M -> UI : asks to create a new category
    activate UI

        UI --> M : requests data (designation)
    deactivate UI

    M -> UI : types requested data and submits
    activate UI

        UI -> CTRL : createCategory(categoryDTO)
        activate CTRL

            CTRL -> SERV : createCategory(categoryDTO)
            activate SERV

                    SERV -> MAPPER : toEntity(categoryDTO)
                activate MAPPER

                    MAPPER -->> CATEGORY**: create()

                    MAPPER --> SERV : category
                deactivate MAPPER
                SERV -> REPO : save(category)

                activate REPO

                    REPO -->> SAVEDCATEGORY**: create()

                    REPO --> SERV : savedCategory
                deactivate REPO

                SERV -> MAPPER : toDTO(savedCategory)
                activate MAPPER
                MAPPER -->> SAVEDDTO**: create()

                MAPPER -> SERV : savedDTO
                deactivate MAPPER

                SERV --> CTRL : savedCategory
            deactivate SERV

            CTRL --> UI : savedCategory
        deactivate CTRL

        UI --> M : displays operation success
    deactivate UI

deactivate M

@enduml
