@startuml
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
skinparam classAttributeIconSize 0


class RequestUI {
}

class RequestController {
    + createRequest()
}

class RequestService {
   + createRequest()
}

interface RequestRepository {
    + save(Request request)
}


class Request {
    - id : String
    - email: String
    - phone: String
    - date: Date
    - status: RequestStatus
    - client: Client
    - advertisement : Advertisement
    + Request(...)
}

enum RequestStatus {
    designation: String
}

class RequestMapper {
    + toEntity(RequestDTO requestDTO))
    + toDTO(Request request))
}

class RequestDTO {
    - id : String
    - email: String
    - phone: String
    - date: Date
    - status: RequestStatus
    - client: Client
    - advertisement : Advertisement
    + RequestDTO(...)
}

class User {
role: client
}

' --- Relacionamentos ---
User .> RequestUI : asks to create\nnew request
RequestUI ..> RequestController
RequestController ..> RequestService
RequestService ..> RequestRepository
RequestService ..> RequestMapper
RequestMapper ..> Request
RequestMapper ..> RequestDTO
RequestRepository "1" --> "*" Request : request
Request "*" --> "1" RequestStatus : has
@enduml