@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

actor "Client" as USER
participant "ReservationAttemptUI" as UI
participant "ReservationAttemptController" as CTRL
participant "ReservationAttemptService" as SERV
participant "mapper\n:ReservationAttemptMapper" as MAPPER
participant "ReservationAttemptsRepository" as AD_REPO
participant "reservationAttempt\n:ReservationAttempt" as ReservationAttempt
participant "reservationAttemptDTO\n:ReservationAttemptDTO" as ReservationAttemptDTO



activate USER

    USER -> UI : ReservationAttempts to create new ReservationAttempt
    activate UI
        UI -> CTRL : createReservationAttempt()
        activate CTRL
            CTRL -> SERV : createReservationAttempt()
            activate SERV
                    SERV -->> ReservationAttempt**: create()
                deactivate MAPPER

                SERV -> AD_REPO : save(ReservationAttempt)
                activate AD_REPO
                    AD_REPO --> SERV : ReservationAttempt
                deactivate AD_REPO

                SERV -> MAPPER : toDTO(ReservationAttempt)
                activate MAPPER
                    MAPPER -->> ReservationAttemptDTO**: create()
                    MAPPER --> SERV : ReservationAttemptDTO
                deactivate MAPPER
                SERV --> CTRL : ReservationAttemptDTO
        deactivate SERV
        CTRL --> UI : ReservationAttemptDTO
        deactivate CTRL
    UI --> USER : ReservationAttemptDTO
    deactivate UI
deactivate USER
@enduml