@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Create Advertisement

autonumber

actor "Client" as Client
participant ":System" as System

activate Client

    Client -> System : requests to create a new advertisement
        activate System

            System --> Client : shows categories list and asks to select one
        deactivate System

        Client -> System : selects a category
        activate System

            System --> Client : requests advertisement data (title, description,\n condition)
        deactivate System

        Client -> System : types requested data and click on Submit button
        activate System

            System --> Client : displays operation success
        deactivate System

deactivate Client
@enduml


