@startuml

title ******* Use Case Come and Get

left to right direction
skinparam actorStyle hollow
  actor "Unregistered\nUser"
  actor "Client"
  actor "Manager"


rectangle " " as usecase1 {

    rectangle "All Users Area " as usecase2 #Lightpink{

            usecase "US09 - View active advertisements" as US09
            usecase "US11 - View advertisement" as US11
            usecase "US12 - Search advertisements" as US12

            "Client" --> US09
            "Client" --> US11
            "Client" --> US12
            "Unregistered\nUser" --> US09
            "Unregistered\nUser" --> US11
            "Unregistered\nUser" --> US12
            "Manager" --> US09
            "Manager" --> US11
            "Manager" --> US12
         }

    rectangle "Unregistered User Area " as usecase3 #Lightgreen{

            usecase "US01 - Register new user" as US01
            usecase "US02 - Login" as US02

            "Unregistered\nUser" --> US01
            "Unregistered\nUser" --> US02
         }

    rectangle "Registered Users (Client/Manager) Area " as usecase4 #Lightcyan{

            usecase "US04 - View categories list" as US04

            "Client" --> US04
            "Manager" --> US04
         }

     rectangle "Client Area " as usecase5 #Lightyellow{


            usecase "US07 - Create advertisement" as US07
            usecase "US13 - Update advertisement" as US13
            usecase "US15 - View my published advertisements" as US15
            usecase "US16 - Create request on advertisement" as US16
            usecase "US17 - View request" as US17
            usecase "US18 - View my request details" as US18
            usecase "US19 - View requests on my advertisements" as US19
            usecase "US20 - Update request" as US20

            "Client" --> US15
            "Client" --> US20
            "Client" --> US18
            "Client" --> US17
            "Client" --> US16
            "Client" --> US15
            "Client" --> US13
            "Client" --> US07

        }

    rectangle "Manager Area " as usecase6 #Lightblue{

            usecase "US03 - Create category" as US03
            usecase "US05 - Update category" as US05
            usecase "US06 - Delete category" as US06
            usecase "US14 - Delete/inactive advertisement" as US14

            "Manager" --> US03
            "Manager" --> US05
            "Manager" --> US06
            "Manager" --> US14
        }
}
@enduml