@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - View available advertisement

autonumber

actor "Logged User" as User
participant ":System" as System

activate User

    User -> System : ask by one specific reservation
    activate System

        System --> User : shows the reservation attempt.
    deactivate System


deactivate User
@enduml