@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

actor "Unregistered User" as User
participant ":RegisterUserUI" as UI
participant ":UserController" as CTRL
participant ":UserService" as UserService
participant ":UserRepository" as UserRepository
participant "user\n:User" as UserModel
participant "userDTO\n:UserDTO" as UserDTO

activate User

    User -> UI : user clicks on signup button
    activate UI

    UI -> User : show signup form
    deactivate UI

    User -> UI : types requested data (name, email, phone number, password, clientType)
    activate UI

    UI ---> User : shows all data and confirm button is enabled.
    deactivate UI

    User -> UI : submits data
    activate UI

        UI -> CTRL : registerUser(name,\nemail, phone number,\npassword, clientType)
        activate CTRL

            CTRL -->> UserDTO**: UserDTO(name, email, phone number,\npassword, clientType)

            CTRL -> UserService : addUser(userDTO)
            activate UserService

            UserService -->> UserModel: toUserEntity(userDTO)

            UserService -> UserRepository: createUser(user)
            activate UserRepository

            UserRepository -> UserRepository: validateUser(user)
            UserRepository -> UserRepository: save(user)
            UserRepository -> UserService: user
            deactivate UserRepository

            UserService -->> UserDTO: toUserDTO(user)
            UserService -> CTRL: userDTO
            deactivate UserService

            CTRL --> UI: userDTO
            deactivate CTRL

            UI --> User: displays operation success
    deactivate UI

deactivate User
@enduml
