@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing true
'skinparam linetype ortho
skinparam classAttributeIconSize 0
hide circle
hide methods
'left to right direction

class Item {
    condition
    image
}

class Category {
    designation
}

class Advertisement {
    - title
    - description
    - date
    - municipality
    - status
}

note bottom of Advertisement
Status: Active, Closed
endnote

Item "0..*" -left- "1" Category : belongs to a \t >
Advertisement "1" -- "1" Item : contains an \t >
@enduml