@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

actor "User" as USER
participant ":AdvertisementUI" as UI
participant ":AdvertisementController" as CTRL
participant ":CategoryService" as CAT_SERVICE
participant ":AdvertisementService" as AD_SERVICE

participant ":AdvertisementMapper" as AD_MAPPER
participant ":ItemRepository" as ITEM_REPO
participant ":CategoryRepository" as CAT_REPO
participant ":AdvertisementRepository" as AD_REPO

participant "updatedAdDto:\nAdvertisementDto" as AD_DTO
participant "updatedItem:\nItem" as ITEM
participant "advertisement:\nAdvertisement" as AD
participant "updatedAdvertisement:\nAdvertisement" as UPDATED_AD

activate USER

    USER -> UI : requests to update an advertisement
    activate UI

        UI -> CTRL : getCategories()
        activate CTRL

            CTRL -> CAT_SERVICE : getAllCategories()
            activate CAT_SERVICE

                CAT_SERVICE -> CAT_REPO : findAll()
                activate CAT_REPO
                    CAT_REPO --> CAT_SERVICE : categoryList
                deactivate CAT_REPO

                CAT_SERVICE --> CTRL : categoryList
            deactivate CAT_SERVICE

            CTRL --> UI : categoryList
        deactivate CTRL

        UI --> USER : shows categories list and asks to select one
    deactivate UI

    USER -> UI : selects a category
    activate UI

        UI --> USER : requests advertisement data \n(designation, finalDate, address, item values)
    deactivate UI

    USER -> UI : types requested data and clicks Submit
    activate UI

        UI -> CTRL : createAdvertisement(advertisementDto)
        activate CTRL

            CTRL -> AD_SERVICE : createAdvertisement(advertisementDto)
            activate AD_SERVICE

                AD_SERVICE -> AD_MAPPER : toEntity(advertisementDto)
                activate AD_MAPPER
                    AD_MAPPER -->> AD** : create()
                    AD_MAPPER --> AD_SERVICE : advertisement
                deactivate AD_MAPPER

                AD_SERVICE -> ITEM_REPO : save(advertisement.item)
                activate ITEM_REPO
                    ITEM_REPO --> AD_SERVICE : savedItem
                deactivate ITEM_REPO

                AD_SERVICE -> AD_REPO : save(advertisement)
                activate AD_REPO
                    AD_REPO --> AD_SERVICE : savedAdvertisement
                deactivate AD_REPO

                AD_SERVICE -> AD_MAPPER : toDto(savedAdvertisement)
                activate AD_MAPPER
                    AD_MAPPER -->> AD_DTO** : create()
                    AD_MAPPER --> AD_SERVICE : savedAdDTO
                deactivate AD_MAPPER

                AD_SERVICE --> CTRL : savedAdDTO
            deactivate AD_SERVICE

            CTRL --> UI : success(savedAdDTO)
        deactivate CTRL

        UI --> USER : displays operation success
    deactivate UI

deactivate USER
@enduml