@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

actor "User" as USER
participant ":AdvertisementUI" as UI

participant "CategoryController" as CAT_CTRL
participant ":CategoryService" as CAT_SERVICE
participant ":CategoryRepository" as CAT_REPO

participant "MunicipalityController" as MUN_CTRL
participant ":MunicipalityWebClient" as MUN_WEBCLIENT

participant ":AdvertisementController" as CTRL
participant ":AdvertisementService" as AD_SERVICE
participant ":AdvertisementMapper" as AD_MAPPER
participant ":ItemRepository" as ITEM_REPO

participant ":AdvertisementRepository" as AD_REPO

participant "createdAdDto:\nAdvertisementDto" as AD_DTO
participant "createdItem:\nItem" as ITEM
participant "createdAdvertisement:\nAdvertisement" as createD_AD

activate USER

    USER -> UI : requests to creata an advertisement
    activate UI

        UI -> CAT_CTRL : getCategories()
        activate CAT_CTRL

            CAT_CTRL -> CAT_SERVICE : getAllCategories()
            activate CAT_SERVICE

                CAT_SERVICE -> CAT_REPO : findAll()
                activate CAT_REPO
                    CAT_REPO --> CAT_SERVICE : categories
                deactivate CAT_REPO

                CAT_SERVICE --> CAT_CTRL : categories
            deactivate CAT_SERVICE

            CAT_CTRL --> UI : categories
        deactivate CAT_CTRL

        UI --> USER : shows categories list and asks to select one
    deactivate UI
        USER -> UI : selects a category
    activate UI

        UI -> MUN_CTRL : getMunicipalities()
        activate MUN_CTRL
            MUN_CTRL -> MUN_WEBCLIENT: getMunicipalities()
            activate MUN_WEBCLIENT
                MUN_WEBCLIENT --> MUN_CTRL : municipalities
                deactivate MUN_WEBCLIENT
                    MUN_CTRL --> UI : municipalities
                    deactivate MUN_CTRL

        UI --> USER : shows municipalities list and asks to select one
    deactivate UI

    USER -> UI : selects a municipality
    activate UI

        UI --> USER : requests created advertisement data \n(title, description, item values)
    deactivate UI

    USER -> UI : types requested data and confirms operation
    activate UI

        UI -> CTRL : createAdvertisement(advertisementDto)
        activate CTRL

            CTRL -> AD_SERVICE : createAdvertisement(advertisementDto)
            activate AD_SERVICE

                AD_SERVICE -> AD_REPO : findById(advertisementDto.id)
                activate AD_REPO
                    AD_REPO --> AD_SERVICE : advertisement
                deactivate AD_REPO

                AD_SERVICE -> AD_SERVICE : createAdvertisement(advertisement)
                activate AD_SERVICE
                    AD_SERVICE --> AD_SERVICE : createdAdvertisement
                deactivate AD_SERVICE

                AD_SERVICE -> ITEM_REPO : save(createdAdvertisement.item)
                activate ITEM_REPO
                    ITEM_REPO -->> ITEM** : create()
                    ITEM_REPO --> AD_SERVICE : createdItem
                deactivate ITEM_REPO

                AD_SERVICE -> AD_REPO : save(createdAdvertisement)
                activate AD_REPO
                    AD_REPO -->> createD_AD** : create()
                    AD_REPO --> AD_SERVICE : createdAdvertisement
                deactivate AD_REPO

                AD_SERVICE -> AD_MAPPER : toDto(createdAdvertisement)
                activate AD_MAPPER
                    AD_MAPPER -->> AD_DTO** : create()
                    AD_MAPPER --> AD_SERVICE : createdAdDTO
                deactivate AD_MAPPER

                AD_SERVICE --> CTRL : createdAdDTO
            deactivate AD_SERVICE

            CTRL --> UI : success(createdAdDTO)
        deactivate CTRL

        UI --> USER : displays operation success
    deactivate UI

deactivate USER
@enduml