@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

actor "Client" as CLIENT
participant ":AdvertisementUI" as UI
participant ":AdvertisementController" as CTRL
participant ":AdvertisementService" as AD_SERVICE

participant ":AdvertisementMapper" as AD_MAPPER
participant ":ItemRepository" as ITEM_REPO
participant ":CategoryRepository" as CAT_REPO
participant ":AdvertisementRepository" as AD_REPO

participant "savedAdDto:\nAdvertisementDto" as AD_DTO
participant "categoryList:\nList<Category>" as CAT_LIST
participant "savedItem:\nItem" as ITEM
participant "advertisement:\nAdvertisement" as AD
participant "savedAdvertisement:\nAdvertisement" as SAVED_AD

activate CLIENT

    CLIENT -> UI : requests to create a new advertisement
    activate UI

        UI -> CTRL : getCategories()
        activate CTRL

            CTRL -> AD_SERVICE : getAllCategories()
            activate AD_SERVICE

                AD_SERVICE -> CAT_REPO : findAll()
                activate CAT_REPO
                    CAT_REPO -->> CAT_LIST** : create()
                    CAT_REPO --> AD_SERVICE : categoryList
                deactivate CAT_REPO

                AD_SERVICE --> CTRL : categoryList
            deactivate AD_SERVICE

            CTRL --> UI : categoryList
        deactivate CTRL

        UI --> CLIENT : shows categories list and asks to select one
    deactivate UI

    CLIENT -> UI : selects a category
    activate UI

        UI --> CLIENT : requests advertisement data (designation, finalDate, address)
    deactivate UI

    CLIENT -> UI : types requested data and clicks Submit
    activate UI

        UI -> CTRL : createAdvertisement(advertisementDto)
        activate CTRL

            CTRL -> AD_SERVICE : createAdvertisement(advertisementDto)
            activate AD_SERVICE

                AD_SERVICE -> AD_MAPPER : toEntity(advertisementDto)
                activate AD_MAPPER
                    AD_MAPPER -->> AD** : create()
                    AD_MAPPER --> AD_SERVICE : advertisement
                deactivate AD_MAPPER

                AD_SERVICE -> ITEM_REPO : save(advertisement.item)
                activate ITEM_REPO
                    ITEM_REPO -->> ITEM** : create()
                    ITEM_REPO --> AD_SERVICE : savedItem
                deactivate ITEM_REPO

                AD_SERVICE -> AD_REPO : save(advertisement)
                activate AD_REPO
                    AD_REPO -->> SAVED_AD** : create()
                    AD_REPO --> AD_SERVICE : savedAdvertisement
                deactivate AD_REPO

                AD_SERVICE -> AD_MAPPER : toDto(savedAdvertisement)
                activate AD_MAPPER
                    AD_MAPPER -->> AD_DTO** : create()
                    AD_MAPPER --> AD_SERVICE : savedAdDTO
                deactivate AD_MAPPER

                AD_SERVICE --> CTRL : savedAdDTO
            deactivate AD_SERVICE

            CTRL --> UI : success(savedAdDTO)
        deactivate CTRL

        UI --> CLIENT : displays operation success
    deactivate UI

deactivate CLIENT
@enduml