0@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

actor "Logged User" as USER
participant ":AdvertisementUI" as UI
participant ":AdvertisementController" as CTRL
participant ":AdvertisementService" as SERVICE
participant ":AdvertisementsRepository" as AD_REPO
participant ":AdvertisementMapper" as MAPPER
participant "advDTO :AdvertisementDTO" as DTO


activate USER

    USER -> UI : requests to deactivate advertisement
    activate UI

    UI --> USER : request confirmation
    deactivate UI

    USER -> UI : confirm
    activate UI

        UI -> CTRL : deactivateAdvertisement(id)
        activate CTRL

            CTRL -> SERVICE : deactivateAdvertisement(id)
            activate SERVICE

            SERVICE -> AD_REPO : findById(id)
            activate AD_REPO
            AD_REPO --> SERVICE :advertisement
            SERVICE -> AD_REPO : deactivateAdvertisement (advertisement)
            AD_REPO --> SERVICE :deactivatedAdvertisement
            deactivate AD_REPO
            SERVICE -> MAPPER: toDto(deactivatedAdvertisement)
            activate MAPPER
            MAPPER -> DTO: create()
            activate DTO
            deactivate DTO
            MAPPER --> SERVICE: return(advDTO :AdvertisementDTO)
            deactivate MAPPER
            SERVICE --> CTRL : advDTO
            deactivate SERVICE

            CTRL --> UI : advDTO (success 200)
        deactivate CTRL

        UI --> USER : display "Advertisement deactivated "
    deactivate UI

deactivate USER
@enduml