@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - View advertisement details

autonumber

actor "Client" as CLT
participant ":System" as System

activate CLT

    CLT -> System : requests to view an advertisement
        activate System

            System --> CLT : displays advertisement
        deactivate System
deactivate CLT
@enduml


