@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Update Advertisement

autonumber

actor "User" as User
participant ":System" as System

activate User

    User -> System : requests to update an advertisement
        activate System

            System --> User : requests updated advertisement data \n(title and description)
        deactivate System

        User -> System : types requested data and confirms operation
        activate System

            System --> User : displays operation success
        deactivate System

deactivate User
@enduml


