@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Update Advertisement

autonumber

actor "Client" as Client
participant ":System" as System

activate Client

    Client -> System : requests to update an advertisement
        activate System

            System --> Client : shows categories list and asks to select one
        deactivate System

        Client -> System : selects a category
        activate System

            System --> Client : requests updated advertisement data (title, \ndescription, condition)
        deactivate System

        Client -> System : types requested data and click on Submit button
        activate System

            System --> Client : displays operation success
        deactivate System

deactivate Client
@enduml


