@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Update Advertisement

autonumber

actor "User" as User
participant ":System" as System

activate User

    User -> System : requests to update an advertisement
        activate System

            System --> User : shows categories list and asks to select one
        deactivate System

        User -> System : selects a category
        activate System

            System --> User : requests updated advertisement data \n(designation, finalDate, address, item values)
        deactivate System

        User -> System : types requested data and click on Submit button
        activate System

            System --> User : displays operation success
        deactivate System

deactivate User
@enduml


